name = "cbl-coverage-api"
main = "coverage-worker.js"
compatibility_date = "2024-01-15"

# KV Namespace binding
[[kv_namespaces]]
binding = "COVERAGE_KV"
id = "be3d02099e6149369eaa820a5a8f9440"

# Environment variables
[vars]
ALLOWED_ORIGIN = "https://cbl-tourney.pages.dev"

# Routes (optional - can use workers.dev subdomain)
# route = { pattern = "api.cbl-tourney.com/*", zone_name = "cbl-tourney.com" }