# Cloudflare Worker configuration for API endpoints
name = "cbl-tourney-api"
main = "workers/api.ts"
compatibility_date = "2025-01-01"

# Worker will be deployed as a standalone service
# Access via: https://cbl-tourney-api.{your-subdomain}.workers.dev/
# Pages will proxy /api/* requests to this Worker

# Enable Node.js compatibility if needed
compatibility_flags = ["nodejs_compat"]

# Environment variables (add your secrets here)
[vars]
ENVIRONMENT = "production"

# Future: Add KV namespaces for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Future: Add D1 database for persistence
# [[d1_databases]]
# binding = "DB"
# database_name = "tourney-db"
# database_id = "your-database-id"

# Future: Add R2 bucket for file storage
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "tourney-storage"