# Cloudflare Pages configuration - Pure Cloudflare, no Vercel
name = "cbl-basketball-tracker"
compatibility_date = "2025-01-01"
pages_build_output_dir = "out"  # Next.js static export directory

# No Node.js compatibility needed for static export
# API routes handled by separate Worker

[placement]
mode = "smart"